version: '2.1'
services:
    webapp:
        build:
          context: .
          dockerfile: dockerfile
        volumes:
          - /tmp/:/tmp/
        depends_on:
          redis:
            condition: service_started
        links:
          - redis
        ports:
            - "8090:80"

    redis:
      image: redis:latest